version: '3.5'
services:
  # RPC daemons
  bitcoin:
    image: vulpemventures/bitcoin:latest
    container_name: bitcoin
    ports:
      - ${BITCOIN_PEER_PORT}:19000
      - ${BITCOIN_NODE_PORT}:19001
    volumes:
      - ./volumes/liquidregtest/config/:/config
    restart: unless-stopped
  liquid:
    image: ghcr.io/vulpemventures/elements:latest
    container_name: liquid
    command:
      - -datadir=config
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
    volumes:
      - ./volumes/liquidregtest/liquid-config/:/config
    restart: unless-stopped
  # Block explorer REST servers
  electrs:
    image: vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:19001
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - bitcoin
    ports:
      - ${BITCOIN_ELECTRS_RPC_PORT}:60401
      - ${BITCOIN_ELECTRS_PORT}:3002
    volumes:
      - ./volumes/liquidregtest/config/:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./volumes/liquidregtest/liquid-config/:/config
    restart: unless-stopped
  # Block explorer frontends
  esplora:
    image: vulpemventures/esplora:latest
    container_name: esplora
    depends_on:
      - chopsticks
    environment:
      API_URL: ${BITCOIN_ESPLORA_URL}
    ports:
      - ${BITCOIN_ESPLORA_PORT}:5000
    restart: unless-stopped
  esplora-liquid:
    image: vulpemventures/esplora:latest
    container_name: esplora-liquid
    depends_on:
      - chopsticks-liquid
    environment:
      API_URL: ${LIQUID_ESPLORA_URL}
    ports:
      - ${LIQUID_ESPLORA_PORT}:5000
    restart: unless-stopped
  # Chopsticks
  chopsticks:
    image: vulpemventures/nigiri-chopsticks:latest
    container_name: chopsticks
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - bitcoin:19001
      - --electrs-addr
      - electrs:3002
      - --addr
      - 0.0.0.0:3000
    depends_on:
      - bitcoin
      - electrs
    ports:
      - ${BITCOIN_CHOPSTICKS_PORT}:3000
    restart: unless-stopped
  chopsticks-liquid:
    image: vulpemventures/nigiri-chopsticks:latest
    container_name: chopsticks-liquid
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - liquid:18884
      - --electrs-addr
      - electrs-liquid:3002
      - --addr
      - 0.0.0.0:3000
      - --chain
      - liquid
    depends_on:
      - liquid
      - electrs-liquid
    ports:
      - ${LIQUID_CHOPSTICKS_PORT}:3000
    restart: unless-stopped
networks:
  default:
    name: nigiri
