workspace:
  base: /root
  path: go/src/github.com/vulpemventures/nigiri

pipeline:
  test:
    image: docker/compose:1.24.0
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - apk update && apk add --no-cache git curl wget bash make build-base
      - mkdir -p /root/go/bin /root/go/pkg
      # Install Go
      - wget -q https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
      - tar -xf go1.13.4.linux-amd64.tar.gz -C /usr/local && rm -rf go*
      - export GOROOT=/usr/local/go
      - export GOPATH=$HOME/go
      - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      # Test
      - export GO111MODULE=on
      - go mod init
      - bash scripts/install
      - go test -v ./...

services:
  docker:
    image: docker:dind
    privileged: true

  compose:
    image: docker/compose:1.24.0
    privileged: true