before:
  hooks:
    - make install
dist: ./build/
builds:
  - main: ./cli/main.go    
    id: nigiri
    binary: .
    ldflags:
    - -s -w -X github.com/vulpemventures/nigiri/cli/cmd.version={{.Version}} -X github.com/vulpemventures/nigiri/cli/cmd.commit={{.Commit}} -X github.com/vulpemventures/nigiri/cli/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    hooks:
      post:
      - cp ./build/"{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}" ./build/"{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
