#!/bin/bash

bash scripts/clean
bash scripts/install
bash scripts/build linux amd64

if [ "$1" == "-p" ]; then
    echo "Will Copy"
    cp build/nigiri-linux-amd64 build/nigiri
    sudo cp build/nigiri /usr/local/bin
fi