#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

OS=$(eval "go env GOOS")
ARCH=$(eval "go env GOARCH")

pushd $PARENT_PATH
mkdir -p build
GO111MODULE=on CGO_ENABLED=0 go build -ldflags="-s -w" -o build/nigiri-$OS-$ARCH cmd/nigiri/*.go
popd
