#!/bin/bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

case $(uname -s) in
  Darwin) OS="darwin";;
  Linux) OS="linux";;
  *) echo "OS $OS not supported"; exit 1;;
esac

case $(uname -m) in
  amd64) ARCH="amd64";;
  x86_64) ARCH="amd64";;
  *) echo "Architecture $ARCH not supported"; exit 1;;
esac

./dist/nigiri_$OS""_$ARCH/nigiri stop --delete &>/dev/null
rm -rf build vendor ~/.nigiri

popd