version: '3'
services:
  # RPC daemon
  bitcoin:
    image: vulpemventures/bitcoin:latest
    networks:
      local:
        ipv4_address: 10.10.0.10
    ports:
      - 19001:19001
    volumes:
      - ./volumes/regtest/config/:/config
  # Block explorer REST server
  electrs:
    image: vulpemventures/electrs:latest
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - 10.10.0.10:19001
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --cors
      - "*"
    networks:
      local:
        ipv4_address: 10.10.0.11
    links:
      - bitcoin
    depends_on:
      - bitcoin
    ports:
      - 3002:3002
    volumes:
      - ./volumes/regtest/config/:/config
  # Block explorer frontend
  esplora:
    image: vulpemventures/esplora:latest
    networks:
      local:
        ipv4_address: 10.10.0.12
    links:
      - electrs
    depends_on:
      - electrs
    ports:
      - 5000:5000
  # Chopsticks
  chopsticks:
    image: vulpemventures/nigiri-chopsticks
    entrypoint:
      - /build/chopsticks
    command:
      - --use-faucet
      - --use-mining
      - --use-logger
      - --rpc-addr
      - 10.10.0.10:19001
      - --electrs-addr
      - 10.10.0.11:3002
      - --addr
      - 0.0.0.0:3000
    networks:
      local:
        ipv4_address: 10.10.0.13
    links:
      - bitcoin
      - electrs
    depends_on:
      - electrs
    ports:
      - 3000:3000

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24